pages:
  stage: deploy
  tags:
    - pages
  script:
    - echo "Copying public dir..."
    - mkdir .public
    - cp -r www/* .public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    - master
